name: 'Goblint'
description: 'The goblint static analysis framework'
author: 'Simmo Saan'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  file:
    description: 'File to analyze'
    required: true
  image:
    description: 'Goblint Docker image to use'
    required: false
    default: 'ghcr.io/goblint/analyzer:nightly'
runs:
  using: 'docker'
  image: 'docker://${{ inputs.image }}'
  args:
    - '--sarif'
    - ${{ inputs.file }}
