name: 'Goblint'
description: 'The goblint static analysis framework'
inputs:
  file:
    description: 'File to analyze'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/goblint/analyzer:latest'
  args:
    - '--sarif'
    - ${{ inputs.file }}
